### ISSUE TITLE
'class BLEAdvertising' has no member named 'setDeviceAddress'; did you mean 'setPrivateAddress'?

### ISSUE THREAD

**Issue by linchengyang1** [ckcr4lyf/EvilAppleJuice-ESP32#16]
My issue is in my title... I know that may be really dumb but I've tried many ways and the problem is still not solved. It's my first time trying to use MCU. Wish you can help me. Thank you.

**Comment by linchengyang1** [comment]
I'm using Arduino 1.8.19, trying to Upload EvilAppleJuice-ESP32-INO to ESP32C3

**Comment by ckcr4lyf** [comment]
@linchengyang1 can you try Visual Studio Code w/ PlatformIO?

**Comment by linchengyang1** [comment]
@ckcr4lyf Thank you! I just succeed!

**Comment by ckcr4lyf** [comment]
Cool, good to hear that.
