### ISSUE TITLE
Successful on iPhone14 pro max 17.2 b3

### ISSUE THREAD

**Issue by Johnnybegood90** [ckcr4lyf/EvilAppleJuice-ESP32#19]

**Comment by ckcr4lyf** [comment]
@Johnnybegood90 thanks for reporting! Can you confirm which ESP32 device you're using (e.g. ESP32C3, S3 etc.)

Is the behavior observed "spammy"? (i.e. keep closing the popup but it keeps coming back).

**Comment by Johnnybegood90** [comment]
Hi.
The board is espwroom32
And yes, it's spammy, it work exactly as expected.

**Comment by ckcr4lyf** [comment]
Added to docs in #20. Thanks.
