### ISSUE TITLE
求问如何提高发射功率？

### ISSUE THREAD

**Issue by tanzhijir-04** [ckcr4lyf/EvilAppleJuice-ESP32#21]

**Comment by ckcr4lyf** [comment]
> 求问如何提高发射功率 -> How to increase transmit power

The following may help: https://github.com/ckcr4lyf/EvilAppleJuice-ESP32/issues/18#issuecomment-1815950744

I've not verified it, but realistically the transmit power would depend more on the model of ESP32 you have and its antenna, I think.

**Comment by ckcr4lyf** [comment]
Closing as no further activity.
