### ISSUE TITLE
Vision pro

### ISSUE THREAD

**Issue by sionk99** [ckcr4lyf/EvilAppleJuice-ESP32#26]
![Uploading IMG_4807.png…]()
能否更新一下这个代码

**Comment by ckcr4lyf** [comment]
Sorry, the photo hasn't seem to be uploaded correctly. Can you try again?

Are you asking for support on the Vision Pro?

**Comment by sionk99** [comment]
![111](https://github.com/ckcr4lyf/EvilAppleJuice-ESP32/assets/29028321/135a11dd-28b1-4618-86d1-1994d7cc4e88)

**Comment by sionk99** [comment]
能否更新一下这个

**Comment by ckcr4lyf** [comment]
Ah, understood. Let me try and find out what the code for it is. Is there any other project you know using it?

**Comment by ckcr4lyf** [comment]
@sionk99 do you have an iPhone? I do not have one so I cannot test it, but maybe you can try changing the 14th byte in the payload of `SHORT_DEVICES` at https://github.com/ckcr4lyf/EvilAppleJuice-ESP32/blob/78984d5f1ff1ca0444caf02ff1cfd9b300c60f0d/src/devices.hpp#L50

It seems this is the changing byte between different devices, so maybe it is possible Vision Pro uses one of these.

![image](https://github.com/ckcr4lyf/EvilAppleJuice-ESP32/assets/6680615/bf8b894e-4165-4d40-b091-0a9c8ede3597)

**Comment by ckcr4lyf** [comment]
Maybe slowly try all of them from 0x00-0xFF... not a great solution but for the time being that is all I can offer. I will try and work on the problem if I get access to an iPhone.

**Comment by sionk99** [comment]
https://github.com/simondankelmann/Bluetooth-LE-Spam        这个项目的，安卓app

**Comment by ckcr4lyf** [comment]
@sionk99 I've made a PR at https://github.com/ckcr4lyf/EvilAppleJuice-ESP32/pull/27 . 

I've not tested this yet so I am not merging it, but you can try and pull that branch and see if it works!

**Comment by ckcr4lyf** [comment]
Added via #27 .
