### ISSUE TITLE
[Suggestion] Raspberry Pi Pico W Port

### ISSUE THREAD

**Issue by ovhx** [ckcr4lyf/EvilAppleJuice-ESP32#4]
Since the Pico W supports BLE 5.0 (for better performance) you could try porting it to micropython and later you also could make a standalone python script

**Comment by ckcr4lyf** [comment]
Python & Linux based bluetooth is already too high level for this project IMO. It is meant to target low level BLE chips where you've a lot more control on the BLE stack. With linux based bluetooth you loose a lot of control.

You're more than welcome to adapt the ideas around randomization from this project into your own though! If you make it let me know, and I can link it in this repo as well.

**Comment by ckcr4lyf** [comment]
Closing since out of scope of this project.
