### ISSUE TITLE
Does it work on ESP32-S3 Development Board 2.4G Wifi Module for Arduino ESP IDF ESP32-S3-WROOM

### ISSUE THREAD

**Issue by theguythatdidsomething** [ckcr4lyf/EvilAppleJuice-ESP32#43]

**Comment by theguythatdidsomething** [comment]
I meant this one ![image](https://github.com/user-attachments/assets/9d13f424-103d-4ce4-9059-14d0a5eb5472)

**Comment by ckcr4lyf** [comment]
As per Espressif, it has BLE, so it should.

![image](https://github.com/user-attachments/assets/d2effb34-938f-4b79-9bf0-e5bdb5f49a27)
