### ISSUE TITLE
I wonder know how do you know about what advertised in airpods or apple TV 

### ISSUE THREAD

**Issue by IAMPIPP** [ckcr4lyf/EvilAppleJuice-ESP32#7]

**Comment by ckcr4lyf** [comment]
@IAMPIPP can you explain your question a bit more? I am having trouble understanding by just the title.

**Comment by IAMPIPP** [comment]
DEVICES,SHORT_DEVICES.How to get  those data？

**Comment by ckcr4lyf** [comment]
From the work of the original authors, you can check it out here: https://github.com/ECTO-1A/AppleJuice

I've just optimized it for randomness and spamming via ESP32

**Comment by IAMPIPP** [comment]
Wow，You have more information than me.And I have changed this program.You did so  well that I learn it completely before.So i think you can do better.China always in one.

**Comment by ckcr4lyf** [comment]
Not quite sure what you're getting at. I'm closing this issue since it seems the initial query has been addressed.
